# Generated by Django 3.2.5 on 2021-10-17 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('next_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_user', to=settings.AUTH_USER_MODEL, verbose_name='上级用户')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
