# Generated by Django 3.2.5 on 2021-10-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PermList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionlist',
            options={'verbose_name': '权限列表', 'verbose_name_plural': '权限列表'},
        ),
    ]
