# Generated by Django 3.2.5 on 2021-10-19 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PermList', '0002_alter_permissionlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlist',
            name='next_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to=settings.AUTH_USER_MODEL, verbose_name='上级用户'),
        ),
        migrations.AlterField(
            model_name='permissionlist',
            name='source_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
