# Generated by Django 3.2.5 on 2021-10-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, verbose_name='公司名称')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='地址')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='电话号码')),
                ('webside', models.CharField(max_length=100, null=True, verbose_name='网站')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('job', models.CharField(max_length=20, null=True, verbose_name='职务')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='地址')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='电话号码')),
                ('mobile_phone', models.CharField(max_length=50, null=True, verbose_name='手机号码')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Email')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contacts.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
    ]
