# Generated by Django 3.2.5 on 2021-10-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='company',
            name='webside',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='网站'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contacts.company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
