# Generated by Django 3.2.5 on 2021-10-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_auto_20211019_1803'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': '产品属性值', 'verbose_name_plural': '产品属性值'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': '产品图片', 'verbose_name_plural': '产品图片'},
        ),
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Contacts.contacts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
    ]
