# Generated by Django 3.2.5 on 2021-10-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20211019_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_style',
            field=models.CharField(max_length=100, null=True, verbose_name='产品款号'),
        ),
    ]
