# Generated by Django 3.2.5 on 2021-10-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20211019_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='Products.ProductAttributeValue', to='Products.ProductAttribute'),
        ),
    ]
